here/* Questions niveau Facile — EDUC National (patriotisme, nouvelle citoyenneté, éducation nationale).
 Une question par ligne : q = question, c = bonne réponse, w = mauvaises réponses, o = ordre imposé (optionnel). */
(window.EDUC_QUESTIONS = window.EDUC_QUESTIONS || {}).facile = [
{"q":"Vous voyez un bien public détérioré : quel est le comportement du bon citoyen ?","c":"Le signaler et le protéger","w":["Vendre sa voix ou semer la violence","Traîner dans la rue","L'ignorer ou l'abîmer davantage"]},
{"q":"Ce comportement est-il civique ? « Le signaler et le protéger »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « L'ignorer ou l'abîmer davantage »","c":"Non","w":["Oui"],"fix":1},
{"q":"L'heure du cours approche : quel est le comportement du bon citoyen ?","c":"Arriver à l'heure","w":["La déchirer","Attiser la haine tribale","Arriver en retard sans raison"]},
{"q":"Ce comportement est-il civique ? « Arriver à l'heure »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Arriver en retard sans raison »","c":"Non","w":["Oui"],"fix":1},
{"q":"Il est temps de payer vos impôts et taxes : quel est le comportement du bon citoyen ?","c":"Les payer honnêtement","w":["Recourir à la violence","La déchirer","Chercher à les éviter"]},
{"q":"Ce comportement est-il civique ? « Les payer honnêtement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Chercher à les éviter »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un agent propose de régler un dossier contre un pot-de-vin : quel est le comportement du bon citoyen ?","c":"Refuser et dénoncer la corruption","w":["Recourir à la violence","Voter selon la tribu","Accepter pour aller plus vite"]},
{"q":"Ce comportement est-il civique ? « Refuser et dénoncer la corruption »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Accepter pour aller plus vite »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous avez des déchets à jeter : quel est le comportement du bon citoyen ?","c":"Les mettre à la poubelle","w":["Détourner une partie de l'argent","La déchirer","Les jeter dans la rue ou le caniveau"]},
{"q":"Ce comportement est-il civique ? « Les mettre à la poubelle »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Les jeter dans la rue ou le caniveau »","c":"Non","w":["Oui"],"fix":1},
{"q":"On lève le drapeau et on chante l'hymne national : quel est le comportement du bon citoyen ?","c":"Se tenir debout avec respect","w":["Recourir à la violence","Chercher à les éviter","Bavarder ou s'asseoir"]},
{"q":"Ce comportement est-il civique ? « Se tenir debout avec respect »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Bavarder ou s'asseoir »","c":"Non","w":["Oui"],"fix":1},
{"q":"Une élection est organisée : quel est le comportement du bon citoyen ?","c":"Voter librement et pacifiquement","w":["L'ignorer ou l'abîmer davantage","Traîner dans la rue","Vendre sa voix ou semer la violence"]},
{"q":"Ce comportement est-il civique ? « Voter librement et pacifiquement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Vendre sa voix ou semer la violence »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un camarade est en difficulté dans ses études : quel est le comportement du bon citoyen ?","c":"L'aider avec solidarité","w":["Voter selon la tribu","Rouler sans respecter les règles","Se moquer de lui"]},
{"q":"Ce comportement est-il civique ? « L'aider avec solidarité »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Se moquer de lui »","c":"Non","w":["Oui"],"fix":1},
{"q":"Le quartier organise le salongo (travail communautaire) : quel est le comportement du bon citoyen ?","c":"Y participer","w":["Les insulter","Passer devant les autres","Laisser les autres faire"]},
{"q":"Ce comportement est-il civique ? « Y participer »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Laisser les autres faire »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un examen approche : quel est le comportement du bon citoyen ?","c":"Rester honnête et réviser","w":["Recourir à la violence","Le déchirer ou le garder","Copier sur le voisin"]},
{"q":"Ce comportement est-il civique ? « Rester honnête et réviser »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Copier sur le voisin »","c":"Non","w":["Oui"],"fix":1},
{"q":"Une personne âgée traverse difficilement la route : quel est le comportement du bon citoyen ?","c":"L'aider avec respect","w":["Jeter des déchets dans le caniveau","Se moquer de son accent","Passer sans s'arrêter"]},
{"q":"Ce comportement est-il civique ? « L'aider avec respect »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Passer sans s'arrêter »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous recevez une fausse information sur les réseaux sociaux : quel est le comportement du bon citoyen ?","c":"Vérifier avant de partager","w":["Détourner une partie de l'argent","Encourager la haine","La partager sans vérifier"]},
{"q":"Ce comportement est-il civique ? « Vérifier avant de partager »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « La partager sans vérifier »","c":"Non","w":["Oui"],"fix":1},
{"q":"Les murs de l'école sont propres : quel est le comportement du bon citoyen ?","c":"Les préserver","w":["Le suivre","L'isoler à cause de son origine","Y écrire ou y dessiner"]},
{"q":"Ce comportement est-il civique ? « Les préserver »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Y écrire ou y dessiner »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous êtes en désaccord avec un camarade : quel est le comportement du bon citoyen ?","c":"Dialoguer calmement","w":["Dire que l'école ne sert à rien","L'emporter chez soi","Recourir à la violence"]},
{"q":"Ce comportement est-il civique ? « Dialoguer calmement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Recourir à la violence »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous avez un devoir à faire : quel est le comportement du bon citoyen ?","c":"Le faire par vous-même","w":["La déchirer","Vendre sa voix ou semer la violence","Le faire copier par un autre"]},
{"q":"Ce comportement est-il civique ? « Le faire par vous-même »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le faire copier par un autre »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un étranger vous demande son chemin : quel est le comportement du bon citoyen ?","c":"L'orienter avec courtoisie","w":["Y écrire ou y dessiner","Menacer ceux qui pensent autrement","Se moquer de lui"]},
{"q":"Ce comportement est-il civique ? « L'orienter avec courtoisie »","c":"Oui","w":["Non"],"fix":1},
{"q":"La RDC célèbre sa fête nationale : quel est le comportement du bon citoyen ?","c":"Participer dans la dignité","w":["Chercher à les éviter","Faire du bruit et courir","Profiter pour semer le désordre"]},
{"q":"Ce comportement est-il civique ? « Participer dans la dignité »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Profiter pour semer le désordre »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous trouvez du matériel scolaire public abandonné : quel est le comportement du bon citoyen ?","c":"Le remettre à la direction","w":["Copier sur le voisin","Abandonner et copier","Le garder pour soi"]},
{"q":"Ce comportement est-il civique ? « Le remettre à la direction »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le garder pour soi »","c":"Non","w":["Oui"],"fix":1},
{"q":"Il y a une file d'attente : quel est le comportement du bon citoyen ?","c":"Attendre son tour","w":["Recourir à la violence","Faire du bruit et courir","Passer devant les autres"]},
{"q":"Ce comportement est-il civique ? « Attendre son tour »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Passer devant les autres »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous utilisez l'eau et l'électricité publiques : quel est le comportement du bon citoyen ?","c":"Les utiliser sans gaspiller","w":["Participer au branchement","Traîner dans la rue","Les gaspiller ou les voler"]},
{"q":"Ce comportement est-il civique ? « Les utiliser sans gaspiller »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Les gaspiller ou les voler »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un ami propose de quitter l'école pour la rue : quel est le comportement du bon citoyen ?","c":"L'encourager à étudier","w":["Répandre des rumeurs","En prendre l'argent","Le suivre"]},
{"q":"Ce comportement est-il civique ? « L'encourager à étudier »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le suivre »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un conflit éclate entre communautés : quel est le comportement du bon citoyen ?","c":"Prôner la paix et l'unité nationale","w":["Chercher à les éviter","Encourager la haine","Attiser la haine tribale"]},
{"q":"Ce comportement est-il civique ? « Prôner la paix et l'unité nationale »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Attiser la haine tribale »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous trouvez un portefeuille perdu : quel est le comportement du bon citoyen ?","c":"Le rendre à son propriétaire ou à la police","w":["Les gaspiller ou les voler","Accepter pour aller plus vite","En prendre l'argent"]},
{"q":"Ce comportement est-il civique ? « Le rendre à son propriétaire ou à la police »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « En prendre l'argent »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous utilisez la route publique : quel est le comportement du bon citoyen ?","c":"Respecter le code de la route","w":["Se moquer de lui","Chercher à les éviter","Rouler sans respecter les règles"]},
{"q":"Ce comportement est-il civique ? « Respecter le code de la route »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Rouler sans respecter les règles »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous voyez un enfant harcelé à l'école : quel est le comportement du bon citoyen ?","c":"Le défendre et prévenir un adulte","w":["L'ignorer","Le suivre","Rire avec les harceleurs"]},
{"q":"Ce comportement est-il civique ? « Le défendre et prévenir un adulte »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Rire avec les harceleurs »","c":"Non","w":["Oui"],"fix":1},
{"q":"Le cours est difficile à comprendre : quel est le comportement du bon citoyen ?","c":"Poser des questions au professeur","w":["Chercher à les éviter","Se moquer de lui","Abandonner et copier"]},
{"q":"Ce comportement est-il civique ? « Poser des questions au professeur »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Abandonner et copier »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous recevez un bulletin avec de mauvaises notes : quel est le comportement du bon citoyen ?","c":"Redoubler d'efforts","w":["Les encourager à se battre","Faire du bruit et courir","Falsifier le bulletin"]},
{"q":"Ce comportement est-il civique ? « Redoubler d'efforts »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Falsifier le bulletin »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un camarade parle une autre langue nationale que vous : quel est le comportement du bon citoyen ?","c":"Le respecter et apprendre de lui","w":["L'ignorer ou l'abîmer davantage","Falsifier le bulletin","Se moquer de son accent"]},
{"q":"Ce comportement est-il civique ? « Le respecter et apprendre de lui »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Se moquer de son accent »","c":"Non","w":["Oui"],"fix":1},
{"q":"On parle du drapeau national : quel est le comportement du bon citoyen ?","c":"Le respecter et en expliquer le sens","w":["Laisser les autres faire","Rire avec les harceleurs","Le salir ou le piétiner"]},
{"q":"Ce comportement est-il civique ? « Le respecter et en expliquer le sens »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le salir ou le piétiner »","c":"Non","w":["Oui"],"fix":1},
{"q":"Des ressources du pays sont exploitées illégalement : quel est le comportement du bon citoyen ?","c":"Dénoncer et protéger les richesses du pays","w":["Voter selon la tribu","Le garder pour soi","Y participer pour gagner de l'argent"]},
{"q":"Ce comportement est-il civique ? « Dénoncer et protéger les richesses du pays »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Y participer pour gagner de l'argent »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un professeur est absent et la classe est agitée : quel est le comportement du bon citoyen ?","c":"Rester calme et réviser","w":["Se moquer de lui","Ne jamais s'intéresser à l'école","Faire du bruit et courir"]},
{"q":"Ce comportement est-il civique ? « Rester calme et réviser »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Faire du bruit et courir »","c":"Non","w":["Oui"],"fix":1},
{"q":"L'école organise un reboisement : quel est le comportement du bon citoyen ?","c":"Participer à la plantation d'arbres","w":["Abandonner et copier","Se moquer de lui","Couper les arbres de l'école"]},
{"q":"Ce comportement est-il civique ? « Participer à la plantation d'arbres »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Couper les arbres de l'école »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un camarade perd son cahier : quel est le comportement du bon citoyen ?","c":"Lui prêter le vôtre","w":["Se moquer de lui","Le salir ou le piétiner","Le cacher pour rire"]},
{"q":"Ce comportement est-il civique ? « Lui prêter le vôtre »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le cacher pour rire »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous voyez un feu de brousse : quel est le comportement du bon citoyen ?","c":"Alerter les autorités et aider à l'éteindre","w":["Répandre des rumeurs","Détourner une partie de l'argent","Regarder sans rien faire"]},
{"q":"Ce comportement est-il civique ? « Alerter les autorités et aider à l'éteindre »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Regarder sans rien faire »","c":"Non","w":["Oui"],"fix":1},
{"q":"On vous demande de payer sans reçu : quel est le comportement du bon citoyen ?","c":"Exiger un reçu officiel","w":["Dire que l'école ne sert à rien","Le déchirer ou le garder","Payer sans rien dire"]},
{"q":"Ce comportement est-il civique ? « Exiger un reçu officiel »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Payer sans rien dire »","c":"Non","w":["Oui"],"fix":1},
{"q":"Votre quartier manque d'hygiène : quel est le comportement du bon citoyen ?","c":"Participer à l'assainissement","w":["La déformer par intérêt","L'emporter chez soi","Jeter des déchets dans le caniveau"]},
{"q":"Ce comportement est-il civique ? « Participer à l'assainissement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Jeter des déchets dans le caniveau »","c":"Non","w":["Oui"],"fix":1},
{"q":"On élit le chef de classe : quel est le comportement du bon citoyen ?","c":"Voter pour le plus compétent","w":["Falsifier le bulletin","Chercher à s'enrichir par la fraude","Voter selon la tribu"]},
{"q":"Ce comportement est-il civique ? « Voter pour le plus compétent »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Voter selon la tribu »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous voyez une affiche officielle : quel est le comportement du bon citoyen ?","c":"La respecter et la lire","w":["Les gaspiller ou les voler","Couper les arbres de l'école","La déchirer"]},
{"q":"Ce comportement est-il civique ? « La respecter et la lire »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « La déchirer »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un élève arrive d'une autre province : quel est le comportement du bon citoyen ?","c":"L'accueillir chaleureusement","w":["Couper les arbres de l'école","Se moquer de son accent","L'isoler à cause de son origine"]},
{"q":"Ce comportement est-il civique ? « L'accueillir chaleureusement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « L'isoler à cause de son origine »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous empruntez un livre à la bibliothèque : quel est le comportement du bon citoyen ?","c":"Le rendre à temps et en bon état","w":["Menacer ceux qui pensent autrement","Les jeter dans la rue ou le caniveau","Le déchirer ou le garder"]},
{"q":"Ce comportement est-il civique ? « Le rendre à temps et en bon état »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Le déchirer ou le garder »","c":"Non","w":["Oui"],"fix":1},
{"q":"Ce sont les vacances : quel est le comportement du bon citoyen ?","c":"Réviser et aider sa communauté","w":["Le garder pour soi","Dire que l'école ne sert à rien","Traîner dans la rue"]},
{"q":"Ce comportement est-il civique ? « Réviser et aider sa communauté »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Traîner dans la rue »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un voisin est malade : quel est le comportement du bon citoyen ?","c":"Lui rendre visite et l'aider","w":["Recourir à la violence","Dire que l'école ne sert à rien","L'ignorer"]},
{"q":"Ce comportement est-il civique ? « Lui rendre visite et l'aider »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « L'ignorer »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous parlez des autorités du pays : quel est le comportement du bon citoyen ?","c":"Les critiquer avec respect et arguments","w":["La déformer par intérêt","Recourir à la violence","Les insulter"]},
{"q":"Ce comportement est-il civique ? « Les critiquer avec respect et arguments »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Les insulter »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un camarade propose d'acheter les sujets d'examen : quel est le comportement du bon citoyen ?","c":"Refuser et le signaler","w":["Répandre des rumeurs","Voter selon la tribu","Acheter les sujets"]},
{"q":"Ce comportement est-il civique ? « Refuser et le signaler »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Acheter les sujets »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous êtes témoin d'un accident : quel est le comportement du bon citoyen ?","c":"Porter secours et appeler les secours","w":["Y participer pour gagner de l'argent","En prendre l'argent","Filmer sans aider"]},
{"q":"Ce comportement est-il civique ? « Porter secours et appeler les secours »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Filmer sans aider »","c":"Non","w":["Oui"],"fix":1},
{"q":"Une campagne de vaccination est organisée : quel est le comportement du bon citoyen ?","c":"Y participer et sensibiliser","w":["Le garder pour soi","Passer sans s'arrêter","Répandre des rumeurs"]},
{"q":"Ce comportement est-il civique ? « Y participer et sensibiliser »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Répandre des rumeurs »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un enseignant vous corrige : quel est le comportement du bon citoyen ?","c":"Écouter et accepter la correction","w":["Falsifier le bulletin","La partager sans vérifier","Répondre avec insolence"]},
{"q":"Ce comportement est-il civique ? « Écouter et accepter la correction »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Répondre avec insolence »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous voyez un enfant non scolarisé : quel est le comportement du bon citoyen ?","c":"Encourager ses parents à l'inscrire","w":["Copier sur le voisin","Bavarder ou s'asseoir","Dire que l'école ne sert à rien"]},
{"q":"Ce comportement est-il civique ? « Encourager ses parents à l'inscrire »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Dire que l'école ne sert à rien »","c":"Non","w":["Oui"],"fix":1},
{"q":"Le pays célèbre ses héros nationaux : quel est le comportement du bon citoyen ?","c":"Leur rendre hommage avec dignité","w":["Les insulter","Le garder pour soi","Les ridiculiser"]},
{"q":"Ce comportement est-il civique ? « Leur rendre hommage avec dignité »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Les ridiculiser »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous préparez votre avenir professionnel : quel est le comportement du bon citoyen ?","c":"Se former pour servir son pays","w":["Les jeter dans la rue ou le caniveau","Couper sans cesse la parole","Chercher à s'enrichir par la fraude"]},
{"q":"Ce comportement est-il civique ? « Se former pour servir son pays »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Chercher à s'enrichir par la fraude »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous gérez la caisse de la classe : quel est le comportement du bon citoyen ?","c":"La gérer avec transparence","w":["Se moquer de lui","Encourager la haine","Détourner une partie de l'argent"]},
{"q":"Ce comportement est-il civique ? « La gérer avec transparence »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Détourner une partie de l'argent »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un débat est organisé en classe : quel est le comportement du bon citoyen ?","c":"Écouter l'avis des autres","w":["Laisser les autres faire","Menacer ceux qui pensent autrement","Couper sans cesse la parole"]},
{"q":"Ce comportement est-il civique ? « Écouter l'avis des autres »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Couper sans cesse la parole »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un panneau de signalisation est tombé : quel est le comportement du bon citoyen ?","c":"Le signaler à la mairie","w":["Le salir ou le piétiner","Y participer pour gagner de l'argent","L'emporter chez soi"]},
{"q":"Ce comportement est-il civique ? « Le signaler à la mairie »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « L'emporter chez soi »","c":"Non","w":["Oui"],"fix":1},
{"q":"Votre opinion politique diffère de la majorité : quel est le comportement du bon citoyen ?","c":"L'exprimer pacifiquement","w":["Les insulter","Se moquer de lui","Menacer ceux qui pensent autrement"]},
{"q":"Ce comportement est-il civique ? « L'exprimer pacifiquement »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Menacer ceux qui pensent autrement »","c":"Non","w":["Oui"],"fix":1},
{"q":"Des élèves se battent : quel est le comportement du bon citoyen ?","c":"Les séparer et appeler un adulte","w":["Rire avec les harceleurs","Répondre avec insolence","Les encourager à se battre"]},
{"q":"Ce comportement est-il civique ? « Les séparer et appeler un adulte »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Les encourager à se battre »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un voisin vole le courant électrique par branchement illégal : quel est le comportement du bon citoyen ?","c":"Refuser et alerter la société d'électricité","w":["L'isoler à cause de son origine","L'ignorer","Participer au branchement"]},
{"q":"Ce comportement est-il civique ? « Refuser et alerter la société d'électricité »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Participer au branchement »","c":"Non","w":["Oui"],"fix":1},
{"q":"Une réunion de parents d'élèves est convoquée : quel est le comportement du bon citoyen ?","c":"Y participer pour suivre l'école","w":["Se moquer de son accent","L'isoler à cause de son origine","Ne jamais s'intéresser à l'école"]},
{"q":"Ce comportement est-il civique ? « Y participer pour suivre l'école »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Ne jamais s'intéresser à l'école »","c":"Non","w":["Oui"],"fix":1},
{"q":"Vous connaissez l'histoire de votre pays : quel est le comportement du bon citoyen ?","c":"La transmettre aux plus jeunes","w":["L'isoler à cause de son origine","Le suivre","La déformer par intérêt"]},
{"q":"Ce comportement est-il civique ? « La transmettre aux plus jeunes »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « La déformer par intérêt »","c":"Non","w":["Oui"],"fix":1},
{"q":"Une guerre menace une région : quel est le comportement du bon citoyen ?","c":"Soutenir la paix et le dialogue","w":["Passer sans s'arrêter","Les jeter dans la rue ou le caniveau","Encourager la haine"]},
{"q":"Ce comportement est-il civique ? « Soutenir la paix et le dialogue »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « Encourager la haine »","c":"Non","w":["Oui"],"fix":1},
{"q":"Un étranger vous offre un cadeau : quel est le comportement du bon citoyen ?","c":"Le remercier avec courtoisie","w":["Abandonner et copier","Y participer pour gagner de l'argent","L'insulter"]},
{"q":"Ce comportement est-il civique ? « Le remercier avec courtoisie »","c":"Oui","w":["Non"],"fix":1},
{"q":"Ce comportement est-il civique ? « L'insulter »","c":"Non","w":["Oui"],"fix":1},
{"q":"Quelle est la capitale de la RDC ?","c":"Kinshasa","w":["Lubumbashi","Goma","Kisangani"]},
{"q":"Quelle est la devise nationale de la RDC ?","c":"Justice – Paix – Travail","w":["Unité – Travail – Progrès","Paix – Liberté – Travail","Union – Discipline – Travail"]},
{"q":"Comment s'appelle l'hymne national ?","c":"Debout Congolais","w":["Vers l'avenir","Dieu protège le Congo","Le chant du Congo"]},
{"q":"Quelle est la date de la fête de l'indépendance ?","c":"Le 30 juin","w":["Le 1er janvier","Le 17 mai","Le 24 novembre"]},
{"q":"Quelle est la monnaie de la RDC ?","c":"Le franc congolais","w":["Le zaïre","Le franc CFA","Le dollar congolais"]},
{"q":"Combien de provinces compte la RDC ?","c":"26","w":["11","21","30"]},
{"q":"Quelle est la langue officielle de la RDC ?","c":"Le français","w":["Le lingala","L'anglais","Le swahili"]},
{"q":"De quelle couleur est l'étoile du drapeau ?","c":"Jaune","w":["Blanche","Rouge","Verte"]},
{"q":"Que symbolise le bleu ciel du drapeau ?","c":"La paix","w":["Le sang des martyrs","La richesse du pays","L'avenir radieux"]},
{"q":"Que symbolise le rouge du drapeau ?","c":"Le sang des martyrs","w":["La paix","La richesse du pays","L'avenir radieux"]},
{"q":"Que symbolise l'étoile du drapeau ?","c":"L'avenir radieux","w":["La paix","Le sang des martyrs","La richesse du pays"]},
{"q":"Qui fut le premier Président de la RDC ?","c":"Joseph Kasa-Vubu","w":["Patrice Lumumba","Mobutu Sese Seko","Laurent-Désiré Kabila"]},
{"q":"Qui fut le premier Premier ministre à l'indépendance ?","c":"Patrice Lumumba","w":["Joseph Kasa-Vubu","Moïse Tshombe","Cyrille Adoula"]},
{"q":"Qui est l'actuel Président de la République ?","c":"Félix Tshisekedi","w":["Joseph Kabila","Mobutu Sese Seko","Moïse Katumbi"]},
{"q":"Qui est la Première ministre actuelle ?","c":"Judith Suminwa Tuluka","w":["Raïssa Malu","Sama Lukonde","Bruno Tshibala"]},
{"q":"Quel ministère s'occupe des écoles du pays ?","c":"Éducation nationale et Nouvelle Citoyenneté","w":["Ministère de la Défense","Ministère des Mines","Ministère des Finances"]},
{"q":"Que signifie ECM ?","c":"Éducation civique et morale","w":["École centrale mondiale","Étude des cultures modernes","Enseignement commun mixte"]},
{"q":"À partir de quel âge peut-on voter ?","c":"18 ans","w":["16 ans","21 ans","25 ans"]},
{"q":"Combien de pays voisins la RDC a-t-elle ?","c":"9","w":["6","7","12"]},
{"q":"Quel grand fleuve traverse la RDC ?","c":"Le fleuve Congo","w":["Le Nil","Le Niger","Le Zambèze"]},
{"q":"Que veut dire « Nouvelle Citoyenneté » ?","c":"Adopter des comportements civiques et patriotiques pour bâtir la RDC","w":["Changer de nationalité","Quitter son pays","Oublier l'histoire du pays"]},
{"q":"Que doit faire un élève patriote ?","c":"Étudier, respecter les symboles et servir son pays","w":["Ignorer les lois","Gaspiller les biens publics","Éviter l'école"]},
{"q":"Qu'est-ce que le salongo ?","c":"Un travail communautaire pour le bien de tous","w":["Un jeu traditionnel","Une taxe nationale","Un examen scolaire"]}
];
